
[Settings]
ID = "e3a69291-5590-44bf-84a4-32cad31e861d"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "starwars/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "starwars/build/"
  # This will be your default build command
  command = "yarn build"
